# Generated by Django 5.2.8 on 2025-12-06 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_country_remove_user_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, help_text='If this appointment is a reschedule, link to the original one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reschedules', to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('reschedule_requested', 'Reschedule Requested'), ('rescheduled', 'Rescheduled')], default='requested', max_length=20),
        ),
    ]
