# Generated by Django 5.2.8 on 2025-12-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appointment_rescheduled_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='America/New_York', help_text="IANA timezone name, e.g. 'Europe/London' or 'Asia/Kolkata'.", max_length=50),
        ),
    ]
