# Generated by Django 5.2.8 on 2025-12-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[], default='America/New_York', max_length=50),
        ),
    ]
