# Generated by Django 5.2.8 on 2025-12-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'US Eastern (New York)'), ('Europe/London', 'UK (London)'), ('Asia/Kolkata', 'India Standard Time (IST)')], default='UTC', max_length=50),
        ),
    ]
