# Generated by Django 5.2.8 on 2025-12-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="IANA timezone name, e.g. 'Europe/London' or 'Asia/Kolkata'.", max_length=50),
        ),
    ]
